import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import type { FunctionComponent } from '@/common/types';

const HERO_BG = '/generated/hero-bg.png';

export const Hero = (): FunctionComponent => {
  return (
    <section id="hero" data-sec="hero" className="relative overflow-hidden">
      {/* Full-bleed hero background photo */}
      <img
        src={HERO_BG}
        alt="Cinematic still generated by VidSlack"
        className="absolute inset-0 h-full w-full object-cover"
        loading="eager"
      />
      {/* Aurora wash + dark overlay so headline/CTA stay readable — composed
          from theme tokens (primary / accent / secondary), never a flat color. */}
      <div
        aria-hidden="true"
        className="absolute inset-0"
        style={{
          background:
            'radial-gradient(95% 75% at 8% 4%, color-mix(in srgb, var(--primary) 55%, transparent) 0%, transparent 62%), ' +
            'radial-gradient(80% 65% at 88% 6%, color-mix(in srgb, var(--accent) 45%, transparent) 0%, transparent 64%), ' +
            'radial-gradient(85% 80% at 58% 108%, color-mix(in srgb, var(--secondary) 55%, transparent) 0%, transparent 66%), ' +
            'linear-gradient(180deg, color-mix(in srgb, var(--background) 60%, transparent), color-mix(in srgb, var(--background) 92%, transparent))',
        }}
      />
      <div
        data-edit-id="hero:div:0"
        aria-hidden="true"
        className="pointer-events-none absolute right-[-10%] top-[22%] h-[60%] w-[70%] opacity-70 blur-3xl"
        style={{ background: 'radial-gradient(closest-side, color-mix(in srgb, var(--accent) 60%, transparent), transparent 78%)' }}
      />

      <div data-edit-id="hero:div:1" className="relative z-10 mx-auto grid w-full max-w-[1240px] gap-10 px-6 py-20 sm:px-10 sm:py-28">
        <p data-edit-id="hero:p:2" className="text-xs font-semibold uppercase tracking-[0.16em] text-muted-foreground">
          Text → video · Image → video · Posted to your channel
        </p>
        <h1
          data-edit-id="hero:h1:3"
          className="max-w-[22ch] font-display text-4xl font-light tracking-[-0.03em] text-foreground sm:text-6xl lg:text-7xl"
        >
          Prompt a video. Post it to Slack.
        </h1>

        <div data-edit-id="hero:div:4" className="grid items-end gap-10 lg:grid-cols-[4fr_7fr]">
          <div data-edit-id="hero:div:5" className="grid gap-5">
            <p data-edit-id="hero:p:6" className="text-lg leading-snug text-foreground">
              VidSlack renders clips from a line of text or a single image, then drops the finished file in the channel you
              chose. No exporting, no re-uploading.
            </p>
            <div data-edit-id="hero:div:7" className="flex flex-wrap gap-3">
              <Button
                data-edit-id="hero:a:8"
                asChild
                size="lg"
                className="w-full text-xs font-semibold uppercase tracking-[0.08em] sm:w-auto"
              >
                <Link to="/signup">Connect your workspace</Link>
              </Button>
              <Button
                data-edit-id="hero:a:9"
                asChild
                variant="outline"
                size="lg"
                className="w-full text-xs font-semibold uppercase tracking-[0.08em] sm:w-auto"
              >
                <a href="#how">See how it works</a>
              </Button>
            </div>
            <p data-edit-id="hero:p:10" className="text-xs font-semibold uppercase tracking-[0.14em] text-muted-foreground">
              Average render 52s · 1080p MP4 · 5–12s clips
            </p>
          </div>

          {/* Glass product panel — a drawn Slack thread mockup, kept as real
              markup (not a photo) so it stays the strongest thing on the page. */}
          <div
            data-edit-id="hero:div:11"
            className="w-full overflow-hidden rounded-[4px] border border-foreground/15 bg-card/75 text-card-foreground shadow-2xl backdrop-blur-xl"
          >
            <div data-edit-id="hero:div:12" className="flex items-center justify-between gap-3 border-b border-foreground/10 px-4 py-3">
              <span data-edit-id="hero:span:13" className="font-semibold"># video-drops</span>
              <span data-edit-id="hero:span:14" className="rounded-full bg-primary/20 px-3 py-1 text-xs font-semibold uppercase tracking-[0.1em]">
                Notifications on
              </span>
            </div>
            <div data-edit-id="hero:div:15" className="grid gap-5 p-4">
              <div data-edit-id="hero:div:16" className="flex min-w-0 gap-3">
                <div data-edit-id="hero:div:17" className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-accent text-xs font-semibold text-accent-foreground">
                  MO
                </div>
                <div data-edit-id="hero:div:18" className="min-w-0">
                  <p data-edit-id="hero:p:19" className="flex flex-wrap items-center gap-2 font-semibold">
                    Maya <span data-edit-id="hero:span:20" className="text-xs font-normal tracking-[0.06em] text-muted-foreground">10:14</span>
                  </p>
                  <p data-edit-id="hero:p:21" className="text-card-foreground">
                    Need a vertical teaser for the kombucha launch — dusk, slow drift.
                  </p>
                </div>
              </div>
              <div data-edit-id="hero:div:22" className="flex min-w-0 gap-3">
                <div data-edit-id="hero:div:23" className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-primary text-xs font-semibold text-primary-foreground">
                  VS
                </div>
                <div data-edit-id="hero:div:24" className="min-w-0">
                  <p data-edit-id="hero:p:25" className="flex flex-wrap items-center gap-2 font-semibold">
                    VidSlack{' '}
                    <span data-edit-id="hero:span:26" className="rounded-full bg-secondary px-2 text-xs font-semibold tracking-[0.12em] text-secondary-foreground">
                      App
                    </span>{' '}
                    <span data-edit-id="hero:span:27" className="text-xs font-normal tracking-[0.06em] text-muted-foreground">10:15</span>
                  </p>
                  <p data-edit-id="hero:p:28" className="text-card-foreground">
                    Render complete — &ldquo;Aurora over a berry orchard, slow drift&rdquo;.
                  </p>
                  <div
                    data-edit-id="hero:div:29"
                    className="relative mt-3 grid aspect-video w-full max-w-[420px] place-items-center overflow-hidden rounded-[4px] border border-foreground/10"
                    style={{ background: 'linear-gradient(135deg, var(--primary), var(--accent) 62%, var(--secondary))' }}
                  >
                    <svg width="40" height="40" viewBox="0 0 46 46" aria-hidden="true">
                      <circle cx="23" cy="23" r="22" fill="none" stroke="var(--primary-foreground)" strokeWidth="1.5" opacity="0.85" />
                      <path d="M18 14 L33 23 L18 32 Z" fill="var(--primary-foreground)" />
                    </svg>
                    <span
                      data-edit-id="hero:span:30"
                      className="absolute bottom-2 right-2 rounded-full bg-foreground/60 px-2 text-xs font-semibold text-background"
                    >
                      0:12
                    </span>
                  </div>
                  <p data-edit-id="hero:p:31" className="mt-2 text-xs font-semibold uppercase tracking-[0.1em] text-muted-foreground">
                    aurora-orchard-01.mp4 · 1080p · 18.4 MB
                  </p>
                </div>
              </div>
            </div>
            <div data-edit-id="hero:div:32" className="flex flex-wrap items-center gap-3 border-t border-foreground/10 bg-muted/40 px-4 py-3">
              <span data-edit-id="hero:span:33" className="rounded-full bg-primary px-3 py-1 text-xs font-semibold uppercase tracking-[0.1em] text-primary-foreground">
                Text → Video
              </span>
              <span data-edit-id="hero:span:34" className="min-w-[140px] flex-1 text-muted-foreground">
                Describe your next clip…
              </span>
              <span data-edit-id="hero:span:35" aria-hidden="true" className="flex h-8 w-8 shrink-0 items-center justify-center rounded-[4px] bg-accent font-semibold text-accent-foreground">
                ↑
              </span>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};
